[package]
name = "omocha-rust-bits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "omocha_rust_bits"
crate-type = ["staticlib"]

[dependencies]
